### ISSUE TITLE
Error while training with mode 512

### ISSUE THREAD

**Issue by Mps24-7uk** [rapidrabbit76/PaintsTensorFlow#12]
I have trained a draft model on the custom dataset but getting dimension error for the same dataset while training with mode 512.

![isuue](https://user-images.githubusercontent.com/31795933/108586143-846af480-7372-11eb-90df-1b9d4f28ee9a.png)

Any help would be appreciated. Thanks and Regards you.

**Comment by rapidrabbit76** [comment]
@Mps24-7uk

1. did u modify the data preprocessing module?
2. tell me the tf version, it would be appreciated.
   1. Err is confirmed that it has been resized to 512 based on one side during the pre-processing process.
   2. please tell us the version as users may have changed depending on the version.
