### ISSUE TITLE
hello,where is ‘draft.h5' about  --draft_weights_path and what is this? thank you

### ISSUE THREAD

**Issue by sibadakesi** [rapidrabbit76/PaintsTensorFlow#30]

**Comment by rapidrabbit76** [comment]
hello @sibadakesi 

## "draft.h5" weight file is not provided.


the "draft.h5" weight file should be created by training.

## Two model training steps are required.
1. Train the draft model
2. Train the colorization model

use the weights created in step 1 as "draft.h5" file.

**Comment by sibadakesi** [comment]
Thank you!
