### ISSUE TITLE
Can you give me the permission to download the model?

### ISSUE THREAD

**Issue by fengchexz** [rapidrabbit76/PaintsTensorFlow#9]
Hi~When I download your models from Google driver, it shows that I do not have permission, I have applied for it, could you pass it. Thanks a lot.

**Comment by SP0N9E** [comment]
> Hi~When I download your models from Google driver, it shows that I do not have permission, I have applied for it, could you pass it. Thanks a lot.

did you get the permission?

**Comment by rapidrabbit76** [comment]
@fengchexz @SP0N9E 
Sorry, We will be able to download the model within next week.
